stages:
  - build
  - code-quality

variables:
  DOCKER_HOST: unix:///var/run/docker.sock
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  image: docker:latest
  script:
    - docker build --target ci -f docker/php/Dockerfile -t pizza-backend-ci:latest .
    - docker build --target prod -f docker/php/Dockerfile -t pizza-backend:latest .

phpstan:
  stage: code-quality
  image: pizza-backend-ci:latest
  script:
    - cd /var/www/app
    - ./vendor/bin/phpstan analyse app routes config database

php-cs-fixer:
  stage: code-quality
  image: pizza-backend-ci:latest
  script:
    - cd /var/www/app
    - ./vendor/bin/php-cs-fixer fix --dry-run --diff

rector:
  stage: code-quality
  image: pizza-backend-ci:latest
  script:
    - cd /var/www/app
    - ./vendor/bin/rector process --dry-run

tests:
  stage: code-quality
  image: pizza-backend-ci:latest
  services:
    - postgres:15-alpine
  variables:
    FF_NETWORK_PER_BUILD: "true"
    APP_ENV: testing
    DB_CONNECTION: pgsql
    DB_HOST: postgres
    DB_PORT: 5432
    DB_DATABASE: pizza_app_test
    DB_USERNAME: postgres
    DB_PASSWORD: postgres
    POSTGRES_DB: pizza_app_test
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
  script:
    - cd /var/www/app
    - export APP_KEY=$(php artisan key:generate --show)
    - php artisan jwt:secret --force
    - php artisan migrate --force
    - php artisan test